# Main Application Configuration
server.port=8081



# JPA / Hibernate Common Settings
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# View Configuration
spring.thymeleaf.cache=false