# Main Application Configuration
server.port=8081

# Active profile - switched easily via .env variable ACTIVE_DB
spring.profiles.active=${ACTIVE_DB:mysql}

# JPA / Hibernate Common Settings
spring.jpa.hibernate.ddl-auto=update

# JPA / Hibernate Common Settings
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# View Configuration
spring.thymeleaf.cache=false